// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VShop.Persistences.Context;

#nullable disable

namespace VShop.Persistences.Migrations
{
    [DbContext(typeof(VShopContextDb))]
    [Migration("20260509000001_ImagenesEnBD")]
    partial class ImagenesEnBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // (Snapshot content is maintained in VShopContextDbModelSnapshot)
#pragma warning restore 612, 618
        }
    }
}
